### ISSUE TITLE
How access the given block inside the helper

### ISSUE THREAD

**Issue by nicolas-brousse** [komposable/komponent#78]
I'm looking for using the given block to my component inside the helper. But I didn't found how to retrieve the block.

I used `block_given_to_component?` and that's works, but if I use `@block_given_to_component.call` but it returns me the content of my parent component.

Is it a missing feature? Or a mistake of usage?

**Comment by florentferry** [comment]
Hello @nicolas-brousse,

Can you provide a gist with your use case, I don't get it what you want to achieve.

You can use it in view with `yield` or `@block_given_to_component.call`, and you have access to `block_given_to_component?` in both view and helper. 

You have access to `Proc` in helper too, and you can get the content with `capture_block = capture(&@block_given_to_component) if block_given_to_component?` for example.

I planned to remove `@block_given_to_component` variable in `1.1.5` because it is not documented, but if you have an use case for keep it, let me know, I should restore it in my next PR.

**Comment by nicolas-brousse** [comment]
Hello @florentferry,

The idea is to have component where I can pass property or block for the content like following:

```rb
# frontend/components/button/_button.html.slim
- if link?
  = link_to @href, link_attributes do
    = yield_or_property(:text)

- else
  = button_tag button_attributes do
    = yield_or_property(:text)
```

*Usage*

```rb
= c "button", text: "My button text"
```

or

```rb
= c "button" do
  | My button text
```

If I use `capture_block = capture(&@block_given_to_component) if block_given_to_component?` I have some wired result.
![screen shot 2018-03-29 at 14 34 16](https://user-images.githubusercontent.com/699216/38089031-569852ca-335e-11e8-8d91-5549e7c510a4.png)

I confirm that if I just simply use `yield` in the view I've not this issue.

I'll give you a gist too

**Comment by nicolas-brousse** [comment]
Here is a gist with more content https://gist.github.com/nicolas-brousse/fda23564f0725c14b970a26cd9aed30a

**Comment by florentferry** [comment]
Its an issue on `komponent`. I should fix it, but let me know if that kind of usage is right for your need. 

```rb
def text
  if block_given_to_component?
     @block_given_to_component.call
   else
     @text
  end
end
```

**Comment by florentferry** [comment]
You can use it on `master` branch, let me know it is not working good.

**Comment by nicolas-brousse** [comment]
Wired I have this error ```undefined method `capture' for #<Komponent::ComponentRenderer:0x00007fdc0eb70d58>```.

```
.container(data-controller="container")
  = yield
```

Because of a `yield` usage into on of my component.

I cloned the gem locally to try to understand why.

**Comment by nicolas-brousse** [comment]
No worries it happens. Happy to help to found this bugs :)

But still have issues with usage of `yield`. I tried to remove all my specific code and only use a `yield` in a component view. And it render this:
![screenshot-2018-3-30](https://user-images.githubusercontent.com/699216/38115948-507af5d2-33ae-11e8-9c43-140781ed79e2.png)

I'll look a bit more to be sure I didn't make a mistake.

**Comment by florentferry** [comment]
I revert to old behavior, I think using `yield` instead of `@block_given_to_component` should fix your issue for now.

**Comment by nicolas-brousse** [comment]
Okay. Using `yield` inside the view so?

**Comment by florentferry** [comment]
Yes

```rb
 if block_given_to_component?
     yield
   else
     @text
  end
```

**Comment by nicolas-brousse** [comment]
Okay, thanks.

**Comment by florentferry** [comment]
Hello @nicolas-brousse,

You can try the expected behavior on `component-renderer-fix`, on that branch you can use the method `block_given_to_component` accessible in both view and helper, which contains `nil` or ` proc` if block given. You can use both `yield` and `block_given_to_component.call` to access content passed in. 

Let me know if the behavior is ok for you, and if the method fits well with your needs.

**Comment by nicolas-brousse** [comment]
Thanks @florentferry!

Looks like it works fine now!
